apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-load-test
  labels:
    app: hpa-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-load
  template:
    metadata:
      labels:
        app: hpa-load
    spec:
      containers:
        - name: hpa-load
          image: busybox
          command: ["sh", "-c", "while true; do :; done"]
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
